### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by unficyp** [smart4solutions/apex_tabular_form_cascading_lov#1]
Hi,
the plugin works fine so far.
The problem i have is with pagination. If i paginate to another result set, the tabular form warns me of unsaved changes. After pressing OK, the next result set is loaded but the cascading select lists are not filled correctly (they show the empty values for the lov). 
Is this a bug or am i doing something wrong ?

thanks & regards,
Gerald

**Comment by rmartenss4s** [comment]
Could you get me an example on apex.oracle.com?

preferably with a dev login..

send through r.martens at smart4solutions.nl
