### ISSUE TITLE
Show Value Required

### ISSUE THREAD

**Issue by mariordabreu** [smart4solutions/apex_tabular_form_cascading_lov#2]
Hi there Im trying to get this work, but when I put the Select List of the tabular I cant see the value that is selected, I mean, I can select the one that I want depending of the parent Record of the tabular, but when I submit, I cant see it anymore, Its there, it works all the triggers asociate to that value but I cant see it in my select list, it just show as Null, but in my database it shows the value, What can I do? It can be because is in a Master Detail and Using ROWID?

Thanks!

**Comment by rmartenss4s** [comment]
Please leave an example on apex.oracle.com and inform me about credentials r.martens at smart4solutions.nl

**Comment by mariordabreu** [comment]
Hi, I have create the application but I cant send you the email via info@smart4solutionc.nl, have you any other email where can I send to you the info of the workspace?

**Comment by mariordabreu** [comment]
Hi sir, there I have send it to you the example! Thank you once again!

**Comment by rmartenss4s** [comment]
Mario,

The plugin should be loaded "on-page-load"

Also: you refer to the plugin on a page that has no tabular form. For regular forms you should use the built in "Cascading LOV Parent Item(s)"

**Comment by mariordabreu** [comment]
I know that my Page is a Master Detail and I have the Tabular Form in my Master Detail or I have to have a Page that just have the Tabular Form? Sorry if I dont get it, Im new on it and Im really trying to make it Work!

Thanks for the answer sir!

**Comment by mariordabreu** [comment]
And Another doubt in the "Child query" I have to put the Value that is unique and make it the same as my :l_key_val, Isn't it?

Can you please show me an example in the app that I create cause I tried with a tabular Form and I have the same problem, can you please show me?

Thanks!

**Comment by rmartenss4s** [comment]
I created an example in your app
